name: payroll_system
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0-83.0.dev

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.1
  build_web_compilers: ^4.0.3
  build_test: ^2.1.0
  lints: ^2.0.0

